name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare deployment directory
        run: |
          mkdir -p ./planing_limpio/data
          cp -r data/holidays.json ./planing_limpio/data/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './planing_limpio'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 